In [2]:
import numpy as np
import pandas as pd
import os

## Maybe will come in handy the Z table transform for the data

In [3]:
dataLocation="../Data/StandardizedData"
allcsvs=os.listdir(dataLocation)

In [4]:
for i in range(len(allcsvs)):
    rawData=pd.read_csv(os.path.join(dataLocation,allcsvs[i]))



In [5]:
rawData

Date      Open      High       Low     Close  \
0     2019-10-22 00:00:00+03:00  0.646781  0.652309  0.641253  0.652309   
1     2019-10-23 00:00:00+03:00  0.657837  0.663365  0.646781  0.663365   
2     2019-10-24 00:00:00+03:00  0.663365  0.679949  0.652309  0.663365   
3     2019-10-25 00:00:00+03:00  0.663365  0.663365  0.646781  0.663365   
4     2019-10-28 00:00:00+03:00  0.668893  0.668893  0.663365  0.663365   
...                         ...       ...       ...       ...       ...   
1247  2024-10-16 00:00:00+03:00  4.050000  4.190000  3.990000  4.070000   
1248  2024-10-17 00:00:00+03:00  4.060000  4.160000  4.060000  4.160000   
1249  2024-10-18 00:00:00+03:00  4.170000  4.190000  4.050000  4.190000   
1250  2024-10-21 00:00:00+03:00  4.150000  4.230000  4.140000  4.150000   
1251  2024-10-22 00:00:00+03:00  4.150000  4.290000  4.150000  4.200000   

            Volume  Days_Between  Pct_Change  
0     2.818350e+07           1.0    0.000000  
1     2.861088e+07           1.0    0.016949  
2     2.499212e+07           1.0    0.000000  
3     2.711898e+07           1.0    0.000000  
4     2.624481e+07           3.0    0.000000  
...            ...           ...         ...  
1247  7.700599e+07           1.0    0.004938  
1248  7.597829e+07           1.0    0.022113  
1249  7.844818e+07           1.0    0.007212  
1250  7.101958e+07           3.0   -0.009547  
1251  7.374059e+07           1.0    0.012048  

[1252 rows x 8 columns]

In [6]:
bigData=pd.read_csv(os.path.join(dataLocation,"TUPRS.IS.csv"))

In [7]:
bigData

Date        Open        High         Low  \
0     2019-10-22 00:00:00+03:00   13.359315   13.636250   13.303928   
1     2019-10-23 00:00:00+03:00   13.591937   13.879950   13.503320   
2     2019-10-24 00:00:00+03:00   13.868872   13.935336   13.680556   
3     2019-10-25 00:00:00+03:00   13.802407   14.046109   13.791330   
4     2019-10-28 00:00:00+03:00   14.023957   14.046111   13.791331   
...                         ...         ...         ...         ...   
1247  2024-10-16 00:00:00+03:00  145.800000  147.900000  144.600000   
1248  2024-10-17 00:00:00+03:00  146.900000  148.400000  145.900000   
1249  2024-10-18 00:00:00+03:00  148.000000  149.100000  145.000000   
1250  2024-10-21 00:00:00+03:00  145.000000  146.000000  144.000000   
1251  2024-10-22 00:00:00+03:00  145.000000  147.100000  143.700000   

           Close        Volume  Days_Between  Pct_Change  
0      13.514399  1.370121e+07           1.0    0.000000  
1      13.846717  1.326607e+07           1.0    0.024590  
2      13.780252  1.127835e+07           1.0   -0.004800  
3      14.001801  1.022659e+07           1.0    0.016077  
4      13.791331  8.022633e+06           3.0   -0.015032  
...          ...           ...           ...         ...  
1247  147.200000  1.690909e+07           1.0    0.010295  
1248  147.400000  1.674227e+07           1.0    0.001359  
1249  145.000000  1.523658e+07           1.0   -0.016282  
1250  144.700000  1.510251e+07           3.0   -0.002069  
1251  145.900000  1.473027e+07           1.0    0.008293  

[1252 rows x 8 columns]

In [10]:
combine=pd.concat([rawData,bigData],axis=0)
combine

Date        Open        High         Low  \
0     2019-10-22 00:00:00+03:00    0.646781    0.652309    0.641253   
1     2019-10-23 00:00:00+03:00    0.657837    0.663365    0.646781   
2     2019-10-24 00:00:00+03:00    0.663365    0.679949    0.652309   
3     2019-10-25 00:00:00+03:00    0.663365    0.663365    0.646781   
4     2019-10-28 00:00:00+03:00    0.668893    0.668893    0.663365   
...                         ...         ...         ...         ...   
1247  2024-10-16 00:00:00+03:00  145.800000  147.900000  144.600000   
1248  2024-10-17 00:00:00+03:00  146.900000  148.400000  145.900000   
1249  2024-10-18 00:00:00+03:00  148.000000  149.100000  145.000000   
1250  2024-10-21 00:00:00+03:00  145.000000  146.000000  144.000000   
1251  2024-10-22 00:00:00+03:00  145.000000  147.100000  143.700000   

           Close        Volume  Days_Between  Pct_Change  
0       0.652309  2.818350e+07           1.0    0.000000  
1       0.663365  2.861088e+07           1.0    0.016949  
2       0.663365  2.499212e+07           1.0    0.000000  
3       0.663365  2.711898e+07           1.0    0.000000  
4       0.663365  2.624481e+07           3.0    0.000000  
...          ...           ...           ...         ...  
1247  147.200000  1.690909e+07           1.0    0.010295  
1248  147.400000  1.674227e+07           1.0    0.001359  
1249  145.000000  1.523658e+07           1.0   -0.016282  
1250  144.700000  1.510251e+07           3.0   -0.002069  
1251  145.900000  1.473027e+07           1.0    0.008293  

[2504 rows x 8 columns]

In [13]:
from Scaler import Scaler
scaler=Scaler()
scaled=scaler.fit_transform(combine.drop(columns=["Date","Pct_Change"]).to_numpy())
scaled

array([[6.72169833e-04, 5.84277264e-04, 7.76157846e-04, 6.42982870e-04,
        3.40053174e-02, 0.00000000e+00],
       [7.30618924e-04, 6.42704462e-04, 8.06009863e-04, 7.01435377e-04,
        3.46573615e-02, 0.00000000e+00],
       [7.59843470e-04, 7.30345259e-04, 8.35861881e-04, 7.01435377e-04,
        2.91362587e-02, 0.00000000e+00],
       ...,
       [7.79675580e-01, 7.85079812e-01, 7.80334731e-01, 7.63801855e-01,
        1.42523120e-02, 0.00000000e+00],
       [7.63815661e-01, 7.68697367e-01, 7.74934583e-01, 7.62215770e-01,
        1.40477569e-02, 3.33333333e-01],
       [7.63815661e-01, 7.74510492e-01, 7.73314539e-01, 7.68560109e-01,
        1.34798474e-02, 0.00000000e+00]])

In [15]:
scaled[:5,:4]

array([[0.00067217, 0.00058428, 0.00077616, 0.00064298],
       [0.00073062, 0.0006427 , 0.00080601, 0.00070144],
       [0.00075984, 0.00073035, 0.00083586, 0.00070144],
       [0.00075984, 0.0006427 , 0.00080601, 0.00070144],
       [0.00078907, 0.00067192, 0.00089557, 0.00070144]])

In [16]:
scaled[-6:,:4]

array([[0.76645898, 0.77503896, 0.77493458, 0.76750272],
       [0.76804497, 0.77873822, 0.77817467, 0.77543314],
       [0.77386028, 0.78138055, 0.78519486, 0.77649053],
       [0.77967558, 0.78507981, 0.78033473, 0.76380186],
       [0.76381566, 0.76869737, 0.77493458, 0.76221577],
       [0.76381566, 0.77451049, 0.77331454, 0.76856011]])

In [17]:
from sklearn.preprocessing import StandardScaler

scalerSmall=StandardScaler()
scalerBig=StandardScaler()

smallZ=scalerSmall.fit_transform(rawData.drop(columns=["Date","Pct_Change"]).to_numpy())
bigZ=scalerBig.fit_transform(bigData.drop(columns=["Date","Pct_Change"]).to_numpy())

In [25]:
smallZ[-6:,:4]

array([[0.7776015 , 0.81805875, 0.82745487, 0.87561194],
       [0.86725749, 0.88911863, 0.88487614, 0.88688081],
       [0.87286099, 0.87272019, 0.92507104, 0.93759073],
       [0.93449948, 0.88911863, 0.91932891, 0.95449403],
       [0.92329249, 0.9109832 , 0.97100805, 0.93195629],
       [0.92329249, 0.94378007, 0.97675018, 0.96012847]])

In [23]:
bigZ[-6:,:4]

array([[1.69527595, 1.68463852, 1.70724805, 1.70250251],
       [1.70081731, 1.69737727, 1.71849212, 1.73025379],
       [1.72113563, 1.70647637, 1.74285426, 1.73395396],
       [1.74145394, 1.71921512, 1.72598816, 1.68955191],
       [1.68604036, 1.66280066, 1.70724805, 1.68400166],
       [1.68604036, 1.6828187 , 1.70162602, 1.70620268]])

In [20]:
bigZ.shape, smallZ.shape

((1252, 6), (1252, 6))

In [24]:
scalerFinal=Scaler()
all=np.zeros((2504,6))
all[:1252,:]=smallZ
all[1252:,:]=bigZ
allsc=scalerFinal.fit_transform(all)
allsc[1247:1252,:4]

array([[0.53813538, 0.51908383, 0.55569777, 0.54624784],
       [0.53965969, 0.51481535, 0.56683567, 0.56013821],
       [0.55642705, 0.51908383, 0.56524454, 0.56476834],
       [0.55337844, 0.52477515, 0.57956469, 0.55859484],
       [0.55337844, 0.53331212, 0.58115582, 0.56631171]])

In [22]:
allsc[-6:,:4]

array([[0.76337913, 0.72615642, 0.78357486, 0.76966153],
       [0.76488653, 0.7294723 , 0.78669057, 0.77726312],
       [0.77041367, 0.73184078, 0.79344125, 0.77827666],
       [0.77594081, 0.73515666, 0.7887677 , 0.76611413],
       [0.76086679, 0.72047206, 0.78357486, 0.76459381],
       [0.76086679, 0.72568273, 0.78201701, 0.77067508]])